In [1]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader , random_split,SubsetRandomSampler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from tqdm import tqdm
import pickle
from sklearn.metrics import confusion_matrix, f1_score, accuracy_score, precision_score, recall_score, roc_auc_score
import warnings

In [2]:
train_sample = pd.read_csv("/home/wt/meta_target/data/train_dtV2.csv")
gene_feat = pd.read_csv("/home/wt/meta_target/data/all_train_gene_cpg.csv")
exp = pd.read_csv("/home/data/sda/wt/model_data/cell_gene_exp_vs_normal_filter.csv")
sample_info = pd.read_csv("/home/data/sda/wt/model_data/new_model/cell_net_filter_exp/raw/train_cell_info.csv")

In [3]:
class no_gnn(Dataset):
    def __init__(self, sample_info, gene_info, exp):
        self.sample_info = sample_info
        self.gene_info = gene_info
        self.gene_exp = exp
    def __len__(self):
        return len(self.sample_info)

    def __getitem__(self, idx): ###这个idx 相当于原来 train_dtV2 中的行
        gene = self.sample_info.id[idx]
        cell = self.sample_info.cell[idx]
        feat = torch.tensor(self.gene_info.loc[self.gene_info["id"]==gene].drop(columns=["id"]).values.flatten())
        exp = torch.tensor(self.gene_exp.loc[self.gene_exp["cell"]==cell].drop(columns=["cell"]).values.flatten())
        cell_gene_feat = torch.cat((feat,exp))
        ys = self.sample_info.is_dep[idx]
        return cell_gene_feat, ys, gene, cell

In [4]:
train_dt = no_gnn(train_sample, gene_feat, exp)

from sklearn.model_selection import KFold
import random
splits = KFold(n_splits=10,shuffle=True,random_state=2023052701)

In [5]:
class Net(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.encoder = torch.nn.Sequential(
            torch.nn.Linear(11240, 4096),
            torch.nn.ReLU(),
            torch.nn.Linear(4096, 1024),
            torch.nn.ReLU(),
            torch.nn.Linear(1024, 512),
            torch.nn.ReLU(),
            torch.nn.Linear(512, 64),
            torch.nn.ReLU(),
            torch.nn.Linear(64, 1)
        )

    def forward(self, x):
        x = self.encoder(x)
        return x

In [6]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
loss_op = torch.nn.BCEWithLogitsLoss()

In [7]:
from tqdm import tqdm

def train():
    model.train()

    total_loss = 0
    step = 0 
    for _, data in enumerate(tqdm(train_loader)):
        input_x = data[0].to(device)
        ys = data[1].to(device)
        optimizer.zero_grad()
        pred = model(input_x.float())
        loss = loss_op(
            pred,
            ys.float().reshape(-1, 1),
        )
        total_loss += loss.item() 
        loss.backward()
        optimizer.step()
        step = step + 1
    return total_loss / step


@torch.no_grad()
def test():
    model.eval()

    ys, preds, preds_raw, genes = [], [], [], []
    total_loss = 0
    step = 0 
    for _, data in enumerate(tqdm(test_loader)):
        input_x = data[0].to(device)
        label = data[1].to(device)
        ys.append(label.cpu().detach().numpy())
        out = model(input_x.float())
        loss = loss_op(
            out,
            label.float().reshape(-1, 1),
        )
        total_loss += loss.item() 
        step = step + 1
        preds.append(np.rint(torch.sigmoid(out).cpu().detach().numpy()))
        preds_raw.append(torch.sigmoid(out).cpu().detach().numpy())
        gene_name = np.array(data[2])
        genes.append(gene_name)

    all_preds = np.concatenate(preds).ravel()
    all_labels = np.concatenate(ys).ravel()
    all_preds_raw = np.concatenate(preds_raw).ravel()
    all_genes = np.concatenate(genes).ravel()
    
    res = pd.DataFrame({"preds":all_preds,"preds_raw":all_preds_raw,"label":all_labels,"genes":all_genes})
    calculate_metrics(all_preds, all_labels, epoch, "test")
    return total_loss / step, res


def calculate_metrics(y_pred, y_true, epoch, type):
    print(f"\n Confusion matrix: \n {confusion_matrix(y_true, y_pred)}")
    print(f"F1 Score: {f1_score(y_true, y_pred)}")
    print(f"Accuracy: {accuracy_score(y_true, y_pred)}")
    prec = precision_score(y_true, y_pred)
    rec = recall_score(y_true, y_pred)
    print(f"Precision: {prec}")
    print(f"Recall: {rec}")
    try:
        roc = roc_auc_score(y_true, y_pred)
        print(f"ROC AUC: {roc}")
    except:
        print(f"ROC AUC: notdefined")

In [8]:
for fold, (train_idx,val_idx) in enumerate(splits.split(np.arange(len(sample_info)))):

    print('Fold {}'.format(fold + 1))
    
    fold_train_idx = [i for i, x in enumerate(train_sample.cell.isin(sample_info.cell[train_idx])) if x] 
    fold_test_idx = [i for i, x in enumerate(train_sample.cell.isin(sample_info.cell[val_idx])) if x] 
    
    train_sampler = SubsetRandomSampler(fold_train_idx)
    test_sampler = SubsetRandomSampler(fold_test_idx)
    train_loader = DataLoader(train_dt, batch_size=1024, sampler=train_sampler, num_workers = 12)
    test_loader = DataLoader(train_dt, batch_size=1024, sampler=test_sampler, num_workers = 12)
    
    model = Net().to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
    
    for epoch in range(15):
        loss_train = train()
        print(f"Epoch: {epoch:03d}, Train Loss: {loss_train:.4f}")
        
    loss_test, test_pre = test()
    print(f"Epoch: {epoch:03d}, Test Loss: {loss_test:.4f}")
    test_pre.to_csv("/home/wt/meta_target/data/cv/no_gnn/fold_"+str(fold)+".csv")

Fold 1


100%|██████████| 269/269 [06:35<00:00,  1.47s/it]


Epoch: 000, Train Loss: 0.5874


100%|██████████| 269/269 [06:38<00:00,  1.48s/it]


Epoch: 001, Train Loss: 0.4750


100%|██████████| 269/269 [06:52<00:00,  1.53s/it]


Epoch: 002, Train Loss: 0.3906


100%|██████████| 269/269 [06:40<00:00,  1.49s/it]


Epoch: 003, Train Loss: 0.3589


100%|██████████| 269/269 [06:39<00:00,  1.49s/it]


Epoch: 004, Train Loss: 0.3356


100%|██████████| 269/269 [06:39<00:00,  1.48s/it]


Epoch: 005, Train Loss: 0.3236


100%|██████████| 269/269 [06:37<00:00,  1.48s/it]


Epoch: 006, Train Loss: 0.3162


100%|██████████| 269/269 [06:37<00:00,  1.48s/it]


Epoch: 007, Train Loss: 0.3107


100%|██████████| 269/269 [06:38<00:00,  1.48s/it]


Epoch: 008, Train Loss: 0.3015


100%|██████████| 269/269 [06:39<00:00,  1.49s/it]


Epoch: 009, Train Loss: 0.2984


100%|██████████| 269/269 [06:38<00:00,  1.48s/it]


Epoch: 010, Train Loss: 0.2880


100%|██████████| 269/269 [06:38<00:00,  1.48s/it]


Epoch: 011, Train Loss: 0.2899


100%|██████████| 269/269 [06:38<00:00,  1.48s/it]


Epoch: 012, Train Loss: 0.2834


100%|██████████| 269/269 [06:39<00:00,  1.48s/it]


Epoch: 013, Train Loss: 0.2829


100%|██████████| 269/269 [06:38<00:00,  1.48s/it]


Epoch: 014, Train Loss: 0.2771


100%|██████████| 31/31 [00:49<00:00,  1.60s/it]



 Confusion matrix: 
 [[22179  1907]
 [ 1901  5752]]
F1 Score: 0.7513061650992685
Accuracy: 0.8800214247455811
Precision: 0.7510118814466641
Recall: 0.7516006794721024
ROC AUC: 0.8362130276045225
Epoch: 014, Test Loss: 0.2892
Fold 2


100%|██████████| 271/271 [06:41<00:00,  1.48s/it]


Epoch: 000, Train Loss: 0.6043


100%|██████████| 271/271 [06:41<00:00,  1.48s/it]


Epoch: 001, Train Loss: 0.4512


100%|██████████| 271/271 [06:40<00:00,  1.48s/it]


Epoch: 002, Train Loss: 0.3868


100%|██████████| 271/271 [06:42<00:00,  1.48s/it]


Epoch: 003, Train Loss: 0.3444


100%|██████████| 271/271 [06:43<00:00,  1.49s/it]


Epoch: 004, Train Loss: 0.3308


100%|██████████| 271/271 [06:42<00:00,  1.49s/it]


Epoch: 005, Train Loss: 0.3179


100%|██████████| 271/271 [06:44<00:00,  1.49s/it]


Epoch: 006, Train Loss: 0.3139


100%|██████████| 271/271 [06:43<00:00,  1.49s/it]


Epoch: 007, Train Loss: 0.3078


100%|██████████| 271/271 [06:43<00:00,  1.49s/it]


Epoch: 008, Train Loss: 0.2980


100%|██████████| 271/271 [06:43<00:00,  1.49s/it]


Epoch: 009, Train Loss: 0.2945


100%|██████████| 271/271 [06:43<00:00,  1.49s/it]


Epoch: 010, Train Loss: 0.2890


100%|██████████| 271/271 [06:45<00:00,  1.49s/it]


Epoch: 011, Train Loss: 0.2882


100%|██████████| 271/271 [06:43<00:00,  1.49s/it]


Epoch: 012, Train Loss: 0.2829


100%|██████████| 271/271 [06:43<00:00,  1.49s/it]


Epoch: 013, Train Loss: 0.2795


100%|██████████| 271/271 [06:43<00:00,  1.49s/it]


Epoch: 014, Train Loss: 0.2811


100%|██████████| 30/30 [00:48<00:00,  1.60s/it]



 Confusion matrix: 
 [[22400   559]
 [ 3242  4414]]
F1 Score: 0.6990260511521103
Accuracy: 0.8758451739343459
Precision: 0.8875930022119445
Recall: 0.5765412748171369
ROC AUC: 0.7760967622397893
Epoch: 014, Test Loss: 0.3039
Fold 3


100%|██████████| 270/270 [06:43<00:00,  1.50s/it]


Epoch: 000, Train Loss: 0.6082


100%|██████████| 270/270 [06:43<00:00,  1.49s/it]


Epoch: 001, Train Loss: 0.4571


100%|██████████| 270/270 [06:43<00:00,  1.49s/it]


Epoch: 002, Train Loss: 0.3848


100%|██████████| 270/270 [06:42<00:00,  1.49s/it]


Epoch: 003, Train Loss: 0.3560


100%|██████████| 270/270 [06:43<00:00,  1.49s/it]


Epoch: 004, Train Loss: 0.3324


100%|██████████| 270/270 [06:43<00:00,  1.50s/it]


Epoch: 005, Train Loss: 0.3223


100%|██████████| 270/270 [06:42<00:00,  1.49s/it]


Epoch: 006, Train Loss: 0.3110


100%|██████████| 270/270 [06:42<00:00,  1.49s/it]


Epoch: 007, Train Loss: 0.3070


100%|██████████| 270/270 [30:31<00:00,  6.78s/it]  


Epoch: 008, Train Loss: 0.2981


100%|██████████| 270/270 [32:32<00:00,  7.23s/it]  


Epoch: 009, Train Loss: 0.2934


100%|██████████| 270/270 [29:58<00:00,  6.66s/it] 


Epoch: 010, Train Loss: 0.2922


100%|██████████| 270/270 [11:58<00:00,  2.66s/it] 


Epoch: 011, Train Loss: 0.2896


100%|██████████| 270/270 [06:40<00:00,  1.48s/it]


Epoch: 012, Train Loss: 0.2832


100%|██████████| 270/270 [06:41<00:00,  1.49s/it]


Epoch: 013, Train Loss: 0.2794


100%|██████████| 270/270 [06:41<00:00,  1.49s/it]


Epoch: 014, Train Loss: 0.2799


100%|██████████| 31/31 [00:48<00:00,  1.57s/it]



 Confusion matrix: 
 [[21998  1281]
 [ 3260  4778]]
F1 Score: 0.6778747251188196
Accuracy: 0.8549988823961426
Precision: 0.7885789734279585
Recall: 0.5944264742473252
ROC AUC: 0.769699168649931
Epoch: 014, Test Loss: 0.3351
Fold 4


100%|██████████| 272/272 [06:45<00:00,  1.49s/it]


Epoch: 000, Train Loss: 0.6306


100%|██████████| 272/272 [06:46<00:00,  1.49s/it]


Epoch: 001, Train Loss: 0.4458


100%|██████████| 272/272 [06:45<00:00,  1.49s/it]


Epoch: 002, Train Loss: 0.3848


100%|██████████| 272/272 [06:44<00:00,  1.49s/it]


Epoch: 003, Train Loss: 0.3497


100%|██████████| 272/272 [06:44<00:00,  1.49s/it]


Epoch: 004, Train Loss: 0.3328


100%|██████████| 272/272 [06:45<00:00,  1.49s/it]


Epoch: 005, Train Loss: 0.3220


100%|██████████| 272/272 [06:47<00:00,  1.50s/it]


Epoch: 006, Train Loss: 0.3112


100%|██████████| 272/272 [06:46<00:00,  1.50s/it]


Epoch: 007, Train Loss: 0.3026


100%|██████████| 272/272 [06:47<00:00,  1.50s/it]


Epoch: 008, Train Loss: 0.3011


100%|██████████| 272/272 [06:47<00:00,  1.50s/it]


Epoch: 009, Train Loss: 0.2945


100%|██████████| 272/272 [06:45<00:00,  1.49s/it]


Epoch: 010, Train Loss: 0.2942


100%|██████████| 272/272 [06:45<00:00,  1.49s/it]


Epoch: 011, Train Loss: 0.2869


100%|██████████| 272/272 [06:46<00:00,  1.49s/it]


Epoch: 012, Train Loss: 0.2847


100%|██████████| 272/272 [07:38<00:00,  1.68s/it]


Epoch: 013, Train Loss: 0.2817


100%|██████████| 272/272 [09:32<00:00,  2.10s/it]


Epoch: 014, Train Loss: 0.2784


100%|██████████| 29/29 [00:58<00:00,  2.03s/it]



 Confusion matrix: 
 [[21336   816]
 [ 2389  4426]]
F1 Score: 0.7341793149207929
Accuracy: 0.8893568543515035
Precision: 0.8443342235787867
Recall: 0.6494497432134997
ROC AUC: 0.8063066700899568
Epoch: 014, Test Loss: 0.2737
Fold 5


100%|██████████| 271/271 [08:00<00:00,  1.77s/it]


Epoch: 000, Train Loss: 0.6238


100%|██████████| 271/271 [06:43<00:00,  1.49s/it]


Epoch: 001, Train Loss: 0.4478


100%|██████████| 271/271 [06:44<00:00,  1.49s/it]


Epoch: 002, Train Loss: 0.3826


100%|██████████| 271/271 [06:45<00:00,  1.49s/it]


Epoch: 003, Train Loss: 0.3500


100%|██████████| 271/271 [06:45<00:00,  1.50s/it]


Epoch: 004, Train Loss: 0.3350


100%|██████████| 271/271 [06:45<00:00,  1.50s/it]


Epoch: 005, Train Loss: 0.3176


100%|██████████| 271/271 [06:45<00:00,  1.50s/it]


Epoch: 006, Train Loss: 0.3103


100%|██████████| 271/271 [06:45<00:00,  1.50s/it]


Epoch: 007, Train Loss: 0.3047


100%|██████████| 271/271 [06:46<00:00,  1.50s/it]


Epoch: 008, Train Loss: 0.2982


100%|██████████| 271/271 [06:46<00:00,  1.50s/it]


Epoch: 009, Train Loss: 0.2976


100%|██████████| 271/271 [06:47<00:00,  1.50s/it]


Epoch: 010, Train Loss: 0.2907


100%|██████████| 271/271 [06:47<00:00,  1.50s/it]


Epoch: 011, Train Loss: 0.2857


100%|██████████| 271/271 [06:46<00:00,  1.50s/it]


Epoch: 012, Train Loss: 0.2843


100%|██████████| 271/271 [06:46<00:00,  1.50s/it]


Epoch: 013, Train Loss: 0.2831


100%|██████████| 271/271 [06:44<00:00,  1.49s/it]


Epoch: 014, Train Loss: 0.2793


100%|██████████| 30/30 [00:47<00:00,  1.57s/it]



 Confusion matrix: 
 [[21173  1655]
 [ 2051  5196]]
F1 Score: 0.7371258334515535
Accuracy: 0.8767747298420615
Precision: 0.7584294263611152
Recall: 0.716986339174831
ROC AUC: 0.8222438266752025
Epoch: 014, Test Loss: 0.2976
Fold 6


100%|██████████| 270/270 [06:44<00:00,  1.50s/it]


Epoch: 000, Train Loss: 0.5996


100%|██████████| 270/270 [06:45<00:00,  1.50s/it]


Epoch: 001, Train Loss: 0.4501


100%|██████████| 270/270 [06:44<00:00,  1.50s/it]


Epoch: 002, Train Loss: 0.3790


100%|██████████| 270/270 [06:44<00:00,  1.50s/it]


Epoch: 003, Train Loss: 0.3489


100%|██████████| 270/270 [06:42<00:00,  1.49s/it]


Epoch: 004, Train Loss: 0.3329


100%|██████████| 270/270 [06:43<00:00,  1.50s/it]


Epoch: 005, Train Loss: 0.3219


100%|██████████| 270/270 [06:44<00:00,  1.50s/it]


Epoch: 006, Train Loss: 0.3159


100%|██████████| 270/270 [06:43<00:00,  1.50s/it]


Epoch: 007, Train Loss: 0.3032


100%|██████████| 270/270 [06:44<00:00,  1.50s/it]


Epoch: 008, Train Loss: 0.3020


100%|██████████| 270/270 [06:43<00:00,  1.49s/it]


Epoch: 009, Train Loss: 0.2931


100%|██████████| 270/270 [06:42<00:00,  1.49s/it]


Epoch: 010, Train Loss: 0.2883


100%|██████████| 270/270 [06:43<00:00,  1.49s/it]


Epoch: 011, Train Loss: 0.2882


100%|██████████| 270/270 [06:42<00:00,  1.49s/it]


Epoch: 012, Train Loss: 0.2866


100%|██████████| 270/270 [06:43<00:00,  1.50s/it]


Epoch: 013, Train Loss: 0.2805


100%|██████████| 270/270 [06:43<00:00,  1.49s/it]


Epoch: 014, Train Loss: 0.2791


100%|██████████| 31/31 [00:48<00:00,  1.58s/it]



 Confusion matrix: 
 [[21974  1327]
 [ 2333  5504]]
F1 Score: 0.750477229342787
Accuracy: 0.8824587320958315
Precision: 0.8057385448689797
Recall: 0.7023095572285313
ROC AUC: 0.8226796058748983
Epoch: 014, Test Loss: 0.2883
Fold 7


100%|██████████| 271/271 [06:45<00:00,  1.50s/it]


Epoch: 000, Train Loss: 0.6239


100%|██████████| 271/271 [06:44<00:00,  1.49s/it]


Epoch: 001, Train Loss: 0.4568


100%|██████████| 271/271 [06:44<00:00,  1.49s/it]


Epoch: 002, Train Loss: 0.3855


100%|██████████| 271/271 [06:44<00:00,  1.49s/it]


Epoch: 003, Train Loss: 0.3531


100%|██████████| 271/271 [06:44<00:00,  1.49s/it]


Epoch: 004, Train Loss: 0.3344


100%|██████████| 271/271 [06:44<00:00,  1.49s/it]


Epoch: 005, Train Loss: 0.3206


100%|██████████| 271/271 [06:43<00:00,  1.49s/it]


Epoch: 006, Train Loss: 0.3102


100%|██████████| 271/271 [06:43<00:00,  1.49s/it]


Epoch: 007, Train Loss: 0.3055


100%|██████████| 271/271 [06:44<00:00,  1.49s/it]


Epoch: 008, Train Loss: 0.2983


100%|██████████| 271/271 [06:45<00:00,  1.50s/it]


Epoch: 009, Train Loss: 0.2932


100%|██████████| 271/271 [06:43<00:00,  1.49s/it]


Epoch: 010, Train Loss: 0.2904


100%|██████████| 271/271 [06:45<00:00,  1.49s/it]


Epoch: 011, Train Loss: 0.2855


100%|██████████| 271/271 [06:45<00:00,  1.50s/it]


Epoch: 012, Train Loss: 0.2842


100%|██████████| 271/271 [06:45<00:00,  1.50s/it]


Epoch: 013, Train Loss: 0.2833


100%|██████████| 271/271 [06:45<00:00,  1.49s/it]


Epoch: 014, Train Loss: 0.2777


100%|██████████| 30/30 [00:47<00:00,  1.59s/it]



 Confusion matrix: 
 [[21674  1090]
 [ 2479  5060]]
F1 Score: 0.7392797136386879
Accuracy: 0.8822228822228823
Precision: 0.8227642276422764
Recall: 0.6711765486138745
ROC AUC: 0.8116469634652574
Epoch: 014, Test Loss: 0.2895
Fold 8


100%|██████████| 271/271 [06:45<00:00,  1.50s/it]


Epoch: 000, Train Loss: 0.5714


100%|██████████| 271/271 [06:45<00:00,  1.50s/it]


Epoch: 001, Train Loss: 0.4553


100%|██████████| 271/271 [06:44<00:00,  1.49s/it]


Epoch: 002, Train Loss: 0.3812


100%|██████████| 271/271 [06:44<00:00,  1.49s/it]


Epoch: 003, Train Loss: 0.3552


100%|██████████| 271/271 [06:43<00:00,  1.49s/it]


Epoch: 004, Train Loss: 0.3301


100%|██████████| 271/271 [06:45<00:00,  1.49s/it]


Epoch: 005, Train Loss: 0.3335


100%|██████████| 271/271 [06:44<00:00,  1.49s/it]


Epoch: 006, Train Loss: 0.3150


100%|██████████| 271/271 [06:45<00:00,  1.50s/it]


Epoch: 007, Train Loss: 0.3070


100%|██████████| 271/271 [06:44<00:00,  1.49s/it]


Epoch: 008, Train Loss: 0.3002


100%|██████████| 271/271 [06:44<00:00,  1.49s/it]


Epoch: 009, Train Loss: 0.2958


100%|██████████| 271/271 [06:44<00:00,  1.49s/it]


Epoch: 010, Train Loss: 0.2920


100%|██████████| 271/271 [06:43<00:00,  1.49s/it]


Epoch: 011, Train Loss: 0.2880


100%|██████████| 271/271 [06:44<00:00,  1.49s/it]


Epoch: 012, Train Loss: 0.2888


100%|██████████| 271/271 [06:44<00:00,  1.49s/it]


Epoch: 013, Train Loss: 0.2821


100%|██████████| 271/271 [06:45<00:00,  1.50s/it]


Epoch: 014, Train Loss: 0.2821


100%|██████████| 30/30 [00:46<00:00,  1.56s/it]



 Confusion matrix: 
 [[21532   916]
 [ 2533  4859]]
F1 Score: 0.738057264373054
Accuracy: 0.884416890080429
Precision: 0.8413852813852813
Recall: 0.6573322510822511
ROC AUC: 0.8082634170593009
Epoch: 014, Test Loss: 0.2860
Fold 9


100%|██████████| 270/270 [06:42<00:00,  1.49s/it]


Epoch: 000, Train Loss: 0.5839


100%|██████████| 270/270 [06:42<00:00,  1.49s/it]


Epoch: 001, Train Loss: 0.4556


100%|██████████| 270/270 [06:41<00:00,  1.49s/it]


Epoch: 002, Train Loss: 0.3942


100%|██████████| 270/270 [06:42<00:00,  1.49s/it]


Epoch: 003, Train Loss: 0.3502


100%|██████████| 270/270 [06:41<00:00,  1.49s/it]


Epoch: 004, Train Loss: 0.3352


100%|██████████| 270/270 [06:42<00:00,  1.49s/it]


Epoch: 005, Train Loss: 0.3236


100%|██████████| 270/270 [06:42<00:00,  1.49s/it]


Epoch: 006, Train Loss: 0.3117


100%|██████████| 270/270 [06:42<00:00,  1.49s/it]


Epoch: 007, Train Loss: 0.3019


100%|██████████| 270/270 [06:42<00:00,  1.49s/it]


Epoch: 008, Train Loss: 0.3017


100%|██████████| 270/270 [06:41<00:00,  1.49s/it]


Epoch: 009, Train Loss: 0.2944


100%|██████████| 270/270 [06:42<00:00,  1.49s/it]


Epoch: 010, Train Loss: 0.2880


100%|██████████| 270/270 [06:42<00:00,  1.49s/it]


Epoch: 011, Train Loss: 0.2905


100%|██████████| 270/270 [06:41<00:00,  1.49s/it]


Epoch: 012, Train Loss: 0.2850


100%|██████████| 270/270 [06:42<00:00,  1.49s/it]


Epoch: 013, Train Loss: 0.2817


100%|██████████| 270/270 [06:42<00:00,  1.49s/it]


Epoch: 014, Train Loss: 0.2792


100%|██████████| 31/31 [00:49<00:00,  1.59s/it]



 Confusion matrix: 
 [[22741   767]
 [ 3082  4847]]
F1 Score: 0.7157941371926456
Accuracy: 0.8775646531157553
Precision: 0.8633772711079444
Recall: 0.6113002900744104
ROC AUC: 0.7893365496654169
Epoch: 014, Test Loss: 0.2997
Fold 10


100%|██████████| 269/269 [06:41<00:00,  1.49s/it]


Epoch: 000, Train Loss: 0.5986


100%|██████████| 269/269 [06:42<00:00,  1.50s/it]


Epoch: 001, Train Loss: 0.4676


100%|██████████| 269/269 [06:42<00:00,  1.50s/it]


Epoch: 002, Train Loss: 0.3888


100%|██████████| 269/269 [06:42<00:00,  1.49s/it]


Epoch: 003, Train Loss: 0.3536


100%|██████████| 269/269 [06:41<00:00,  1.49s/it]


Epoch: 004, Train Loss: 0.3343


100%|██████████| 269/269 [06:42<00:00,  1.50s/it]


Epoch: 005, Train Loss: 0.3232


100%|██████████| 269/269 [06:43<00:00,  1.50s/it]


Epoch: 006, Train Loss: 0.3073


100%|██████████| 269/269 [06:43<00:00,  1.50s/it]


Epoch: 007, Train Loss: 0.3070


100%|██████████| 269/269 [06:42<00:00,  1.49s/it]


Epoch: 008, Train Loss: 0.2975


100%|██████████| 269/269 [06:42<00:00,  1.50s/it]


Epoch: 009, Train Loss: 0.2933


100%|██████████| 269/269 [06:42<00:00,  1.50s/it]


Epoch: 010, Train Loss: 0.2898


100%|██████████| 269/269 [06:43<00:00,  1.50s/it]


Epoch: 011, Train Loss: 0.2839


100%|██████████| 269/269 [06:41<00:00,  1.49s/it]


Epoch: 012, Train Loss: 0.2834


100%|██████████| 269/269 [06:42<00:00,  1.50s/it]


Epoch: 013, Train Loss: 0.2778


100%|██████████| 269/269 [06:43<00:00,  1.50s/it]


Epoch: 014, Train Loss: 0.2762


100%|██████████| 31/31 [00:50<00:00,  1.62s/it]



 Confusion matrix: 
 [[21056  2492]
 [ 1825  6362]]
F1 Score: 0.7466697963734522
Accuracy: 0.8639672286119426
Precision: 0.7185452902642874
Recall: 0.7770856235495297
ROC AUC: 0.8356296132016378
Epoch: 014, Test Loss: 0.3281
